name: Build and Deploy Twenty Frontend

on:
  push:
    branches: [main, dev]
    paths:
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
      - 'packages/twenty-shared/**'
      - '.github/workflows/twenty-frontend-deploy.yml'
      - '../../tm-twenty/Dockerfile.frontend'
      - '../../tm-twenty/nginx.conf.template'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/twenty-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=dev-latest,enable=${{ github.ref == 'refs/heads/dev' }}
            type=sha,prefix={{branch}}-
            type=raw,value=coolify,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ../../tm-twenty/Dockerfile.frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REACT_APP_SERVER_BASE_URL=${{ vars.REACT_APP_SERVER_BASE_URL || 'http://localhost:3200' }}

      - name: Deployment complete
        run: |
          echo "## 🚀 Twenty Frontend Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Frontend Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coolify Setup Instructions:" >> $GITHUB_STEP_SUMMARY
          echo "1. In Coolify, create a new Docker service" >> $GITHUB_STEP_SUMMARY
          echo "2. Use image: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "3. Set port: 80 (nginx serves on port 80)" >> $GITHUB_STEP_SUMMARY
          echo "4. Configure health check: /health on port 80" >> $GITHUB_STEP_SUMMARY
          echo "5. Ensure backend service is available at tintmeta-twenty-backend:3200" >> $GITHUB_STEP_SUMMARY
