name: Build and Deploy Twenty Backend

on:
  push:
    branches: [main]
    paths:
      - 'packages/twenty-server/**'
      - 'packages/twenty-emails/**'
      - 'packages/twenty-shared/**'
      - 'packages/trib-messages-module/**'
      - '.github/workflows/twenty-backend-deploy.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/twenty-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=raw,value=coolify,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty/docker/twenty/Dockerfile.backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REACT_APP_SERVER_BASE_URL=${{ vars.REACT_APP_SERVER_BASE_URL || 'http://localhost:3200' }}
            APP_VERSION=${{ github.sha }}

      - name: Deployment complete
        run: |
          echo "## 🚀 Twenty Backend Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Backend Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coolify Setup Instructions:" >> $GITHUB_STEP_SUMMARY
          echo "1. In Coolify, create a new Docker service" >> $GITHUB_STEP_SUMMARY
          echo "2. Use image: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "3. Set port: 3200" >> $GITHUB_STEP_SUMMARY
          echo "4. Add environment variables from your .env file" >> $GITHUB_STEP_SUMMARY
          echo "5. Configure health check: /healthz on port 3200" >> $GITHUB_STEP_SUMMARY